<?php
    // Header
    if(strlen($content->getTitle()) > 1)
    {
        echo '<div class="hero-unit">';
                echo '<h1>'.$content->getTitle().'</h1>';
                echo '<p>'.$content->getSummary().'</p>';
                $img = $this->img($content->getIdWeb(),$size = 'xl');
                echo '<div class="description">'.$content->getContent().'</div>';
        echo '</div>';

        if($img)
        {
            echo '<div class="image">'.$img.'</div>';
        }
    }