<?php

    foreach($content as $c)
    {
        // Header
        if($c->getTitle())
        {
            echo '<h2>'.$c->getTitle().'</h2>';
        }

        if($c->getSummary())
        {
            echo '<p class="summary">'.$c->getSummary().'</p>';
        }

        $img = $this->img($c->getIdWeb(),$size = 'xl');
        if($img)
        {
            echo '<p class="image">'.$img.'</p>';
        }

        // Content
        if($c->getContent())
        {
            echo '<div class="row-fluid">'.$c->getContent().'</div>';
        }
    }
