

<div class="accordion" id="accordion2">

    <?php $cont = 0; foreach($content as $c){ $cont++; ?>

        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#<?=$c->getName()?>">
                    <?=$c->getTitle()?>
                </a>
            </div>
            <div id="<?=$c->getName()?>" class="accordion-body collapse<?php if($cont == 1){ echo ' in'; } ?>">
                <div class="accordion-inner">
                    <h4><?=$c->getSummary()?></h4>
                    <p><?=$this->img($c->getIdWeb(),$size = 'xl')?></p>
                    <?=$c->getContent()?>
                </div>
            </div>
        </div>

    <?php } ?>

</div>
