

<ul id="myTab" class="nav nav-tabs">

    <?php
    $cc = array();
    $count = 0; foreach($content as  $c){ $count++;
        $cc[] = array('summary' =>  $c->getSummary(),
        'id' =>  $c->getIdWeb(),
       'name' =>  $c->getName(),
       'content' =>  $c->getContent());
    ?>

        <li class="<?php if($count == 1){ echo 'active'; }?>">
            <a href="#<?=$c->getName()?>"  data-toggle="tab">
                <?=$c->getTitle()?>
            </a>
        </li>

    <?php } ?>

</ul>
<div id="myTabContent" class="tab-content">

    <?php $count2 = 0;  foreach($cc as $c){ $count2++;  ?>

        <div class="tab-pane fade<?php if($count2 == 1){ echo ' active in'; }?>"  id="<?=$c['name']?>">
             <h5><?=$c['summary']?></h5>
             <p><?=$this->img($c['id'],$size = 'xl')?></p>
             <?=$c['content']?>
        </div>

    <?php } ?>

</div>


