
<div class="row-fluid grid" style="margin-top:20px;">

    <?php

    $grid_fluid = round(12/$grid);
    $count = -1;  foreach($content as $c){ $count++;

    if($count == $grid){ $count = 0;  echo '</div><div class="row-fluid grid">'; }

    ?>
        <div class="span<?=$grid_fluid?>">

            <p><?=$this->img($c->getIdWeb(),$size = 'xl')?></p>

            <h5><?=$c->getTitle()?></h5>

            <p><?=$c->getSummary()?></p>

            <?=$c->getContent()?>

        </div>

    <?php } ?>

</div>
