
    <div class="row-fluid">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-tabs nav-stacked">
                <?php
                     // Sub nav
                     echo $this->partial('qu-web-demo/content/nav-sub.phtml',array(

                            'menu'      =>  $this->cont(false,'all',false,$sub_content->getIdLang()),
                            'parent'    =>  $sub_content->getName()

                    ));
                ?>
            </ul>
        </div>
        <div class="span9">
            <?php

                 echo $this->img($sub_content->getIdWeb(),$size = 'l');

                $content = $this->cont(false,'row','url2',$sub_content->getIdLang());
                if( $content){

                    echo $this->img($content->getIdWeb(),$size = 'l');

                    $this->headTitle()->prepend($content->getTitle());
                    $this->placeholder('url2')->set($content->getName());

                    if($content->getIdParent() != ''){

                        // Head & Content Sub menu
                        echo $this->partial('qu-web-demo/content/page-content.phtml',array('content'=>$content));

                        // Page loops sub menu
                        echo  $this->partial('qu-web-demo/content/page-options.phtml',array('content' => $content));
                    }
                }
            ?>
        </div>
    </div>