<?php

    // Header
    if(strlen($content->getTitle()) > 1)
    {
        echo '<div class="page-header">';

        echo '<h1>'.$content->getTitle().'<br> <small>'.$content->getSummary().'</small></h1>';




        $img = $this->img($content->getIdWeb(),$size = 'xl');

        if($img){

            $img =  '<p class="image">'.$img.'</p>';

        } else{

            $img =  '';

        }

        // Content
        if($content->getContent())
        {
            echo '<div class="row-fluid">
                    <div class="span12">
                    '.$img.'
                    '.$content->getContent().'
                    </div>
                  </div>';
        }

        echo '</div>';


    }