<?php

    if(strlen($content->getTitle()) > 1)
    {

        echo '<div class="content-sub">';

            echo '<h2>'.$content->getTitle().'</h2>';


            if(strlen($content->getTitle()) > 1)
            {
                echo '<p>'.$content->getSummary().'<p>';
            }

            $img = $this->img($content->getIdWeb(),$size = 'xl');

            if($img){

                echo   '<p class="image">'.$img.'</p>';

            }

            if(strlen($content->getTitle()) > 1)
            {
                echo $content->getContent();
            }

        echo '</div>';

    }
?>